"""Placeholder 3 (delivery outputs) constants."""
PAGE_URL = "/vpat-generate-report"
API_VPAT = "/api/feature/vpat"
API_ERRORS = "/api/feature/delivery-errors"
API_PREPARE = "/api/feature/delivery-prepare"
API_EXPORT = "/api/feature/export-template"
API_IMPORT_ASSET = "/api/feature/import-digital-asset"
API_IMPORT_ALT = "/api/feature/import-alt-text"
API_CHECK_PARENT = "/api/feature/check-parent"
PAGE_TITLE = "Validate / Generate Delivery Outputs"
BLUEPRINT_NAME = "vpat_report"
